sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12
cache: npm
branches:
  only:
    - gh-pages # build gh-pages branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}
  keep-history: true
  on:
    branch: master
  local-dir: public

notifications:
  email: true
