
language: node_js

node_js: stable

install:
  - npm install

# before_script:


script:
  - hexo clean
  - hexo generate

after_script:
  - git config --global user.name "ikroskun"
  - git config --global user.email "merle.liukun@gmail.com"
  - sed -i "s/__GITHUB_TOKEN__/${GITHUB_TOKEN}/" _config.yml
  - hexo deploy

branches:
  only:
    - hexo_repo

notifications:
  email: true
