language: node_js

node_js: stable

install:
  - npm install

before_install:
    - git clone --branch=master https://github.com/MerleLiuKun/merleliukun.github.io .deploy_git

script:
  - hexo clean
  - hexo generate

after_script:
  - git config --global user.name "ikaroskun"
  - git config --global user.email "merle.liukun@gmail.com"
  - sed -i "s/__GITHUB_TOKEN__/${GITHUB_TOKEN}/" _config.yml
  - hexo deploy

branches:
  only:
    - gh-pages

notifications:
  email: true